/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./sync.html",
    "./generator.html",
    "./details.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#353534",
        "surface-bright": "#393939",
        "on-primary": "#002e6a",
        "primary-fixed-dim": "#adc6ff",
        "inverse-on-surface": "#313030",
        "inverse-primary": "#005ac2",
        "on-secondary-container": "#a9bad3",
        "tertiary-fixed": "#ffdcc6",
        "background": "#131313",
        "on-tertiary-container": "#461f00",
        "on-primary-fixed-variant": "#004395",
        "on-secondary-fixed-variant": "#38485d",
        "tertiary": "#ffb786",
        "on-secondary": "#213145",
        "on-background": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "surface-tint": "#adc6ff",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-dim": "#131313",
        "on-primary-container": "#00285d",
        "on-error-container": "#ffdad6",
        "on-surface": "#e5e2e1",
        "surface-container": "#201f1f",
        "outline": "#8c909f",
        "secondary-container": "#3a4a5f",
        "error": "#ffb4ab",
        "on-tertiary": "#502400",
        "primary-fixed": "#d8e2ff",
        "primary": "#adc6ff",
        "tertiary-container": "#df7412",
        "on-tertiary-fixed-variant": "#723600",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed": "#d3e4fe",
        "primary-container": "#4d8eff",
        "surface-container-highest": "#353534",
        "secondary": "#b7c8e1",
        "error-container": "#93000a",
        "inverse-surface": "#e5e2e1",
        "on-secondary-fixed": "#0b1c30",
        "on-tertiary-fixed": "#311400",
        "on-surface-variant": "#c2c6d6",
        "on-error": "#690005",
        "outline-variant": "#424754",
        "surface": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed": "#001a42",
        "tertiary-fixed-dim": "#ffb786"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "monospace"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
